# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2019-09-25 14:25
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ('gameplay', '0003_auto_20190924_1621'),
    ]

    operations = [
        migrations.AlterField(
            model_name='move',
            name='by_first_player',
            field=models.BooleanField(editable=False),
        ),
    ]
