# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2019-09-25 14:47
from __future__ import unicode_literals

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ('gameplay', '0004_auto_20190925_1425'),
    ]

    operations = [
        migrations.AlterField(
            model_name='move',
            name='game',
            field=models.ForeignKey(editable=False,
                                    on_delete=django.db.models.deletion.CASCADE,
                                    to='gameplay.Game'),
        ),
    ]
